In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
rng = np.random.default_rng(seed=12345)

In [4]:
draws = rng.standard_normal(1000)

In [5]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [6]:
bins = pd.qcut(draws, 4)

In [7]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [9]:
bins = pd.qcut(draws, 4, labels = ['Q1', 'Q2', 'Q3', 'Q4'])

In [10]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [11]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [12]:
bins = pd.Series(bins, name = 'quartile')

In [13]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())

In [14]:
results

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [15]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [16]:
N = 10_000_000

In [17]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [18]:
categories = labels.astype('category')

In [19]:
labels.memory_usage(deep = True)

520000132

In [20]:
categories.memory_usage(deep = True)

10000340

In [21]:
%time _ = labels.astype('category')

CPU times: total: 1.7 s
Wall time: 1.76 s

In [22]:
%time labels.value_counts()

CPU times: total: 1.67 s
Wall time: 1.76 s

foo    2500000
bar    2500000
baz    2500000
qux    2500000
Name: count, dtype: int64

In [23]:
%timeit categories.value_counts()

112 ms ± 19.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [24]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [25]:
cat_s = s.astype('category')

In [26]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [27]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [28]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='str')

In [29]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [30]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [31]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, str): ['a', 'b', 'c', 'd', 'e']

In [32]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [33]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [34]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [35]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']

In [36]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype = 'category')

In [37]:
pd.get_dummies(cat_s)

       a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True