In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
obj = pd.Series(np.arange(5), index = ["a", "a", "b", "b","c"])

In [5]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [6]:
obj.index.is_unique

False

In [7]:
obj["a"]

a    0
a    1
dtype: int64

In [8]:
obj["c"]

np.int64(4)

In [9]:
df = pd.DataFrame(np.random.standard_normal((5,3)), index = ["a","a","b","b","c"])

In [10]:
df

          0         1         2
a -0.196296 -0.226416  0.547102
a -1.018165 -0.077141 -0.228830
b  0.226313 -0.059610  0.834053
b  0.404203 -1.016798  2.088399
c -1.465323 -0.010106  0.641501

In [11]:
df.loc["b"]

          0         1         2
b  0.226313 -0.059610  0.834053
b  0.404203 -1.016798  2.088399

In [12]:
df.loc["c"]

0   -1.465323
1   -0.010106
2    0.641501
Name: c, dtype: float64

In [13]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan],[0.75, -1.3]], index = ["a","b","c","d"], columns = ["one", "two"])

In [14]:
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [15]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [16]:
df.sum(axis = "columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [17]:
df.sum(axis = "index", skipna = False)

one   NaN
two   NaN
dtype: float64

In [18]:
df.sum(axis = "columns", skipna = False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [19]:
df.mean(axis = "columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [20]:
df.idxmax()

one    b
two    d
dtype: str

In [21]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [22]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [23]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [24]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [25]:
price = pd.read_pickle("examples/yahoo_price.pkl")

FileNotFoundError: [Errno 2] No such file or directory: 'examples/yahoo_price.pkl'

In [27]:
import yfinance as yf
import pandas as pd
import os

# Create examples folder
os.makedirs("examples", exist_ok=True)

# Download data
price = yf.download(
    ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA"],
    start="2015-01-01",
    end="2023-01-01"
)["Close"]

# Save as pickle
price.to_pickle("examples/yahoo_price.pkl")

print("✅ File saved successfully!")
print("Path:", os.path.abspath("examples/yahoo_price.pkl"))

[*********************100%***********************]  5 of 5 completed

✅ File saved successfully!
Path: C:\Users\Ahem\Desktop\pandas\examples\yahoo_price.pkl

In [28]:
price = pd.read_pickle("examples/yahoo_price.pkl")
print(price.head())

Ticker           AAPL     AMZN      GOOGL       MSFT       TSLA
Date
2015-01-02  24.214895  15.4260  26.260456  39.767677  14.620667
2015-01-05  23.532719  15.1095  25.760094  39.402004  14.006000
2015-01-06  23.534933  14.7645  25.124348  38.823689  14.085333
2015-01-07  23.864950  14.9210  25.050459  39.316952  14.063333
2015-01-08  24.781889  15.0230  25.137741  40.473572  14.041333

In [30]:
returns = price.pct_change().dropna()

In [31]:
returns["MSFT"].corr(returns["TSLA"])

np.float64(0.4225541450990672)

In [32]:
returns.tail()

Ticker          AAPL      AMZN     GOOGL      MSFT      TSLA
Date
2022-12-23 -0.002798  0.017425  0.016750  0.002267 -0.017551
2022-12-27 -0.013878 -0.025924 -0.020621 -0.007414 -0.114089
2022-12-28 -0.030686 -0.014692 -0.015677 -0.010255  0.033089
2022-12-29  0.028324  0.028844  0.028249  0.027630  0.080827
2022-12-30  0.002469 -0.002138 -0.002487 -0.004937  0.011164

In [33]:
returns.corr()

Ticker      AAPL      AMZN     GOOGL      MSFT      TSLA
Ticker
AAPL    1.000000  0.584458  0.639100  0.709416  0.428222
AMZN    0.584458  1.000000  0.661297  0.666088  0.401974
GOOGL   0.639100  0.661297  1.000000  0.753071  0.385550
MSFT    0.709416  0.666088  0.753071  1.000000  0.422554
TSLA    0.428222  0.401974  0.385550  0.422554  1.000000

In [34]:
returns.cov()

Ticker      AAPL      AMZN     GOOGL      MSFT      TSLA
Ticker
AAPL    0.000356  0.000231  0.000215  0.000237  0.000289
AMZN    0.000231  0.000440  0.000247  0.000248  0.000301
GOOGL   0.000215  0.000247  0.000318  0.000238  0.000245
MSFT    0.000237  0.000248  0.000238  0.000314  0.000268
TSLA    0.000289  0.000301  0.000245  0.000268  0.001277

In [35]:
returns.corrwith(returns["GOOGL"])

Ticker
AAPL     0.639100
AMZN     0.661297
GOOGL    1.000000
MSFT     0.753071
TSLA     0.385550
dtype: float64

In [40]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b","c", "c"])

In [43]:
uniques = obj.unique()

In [44]:
uniques

<StringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [45]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [47]:
pd.Series(obj.to_numpy()).value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [48]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [49]:
mask = obj.isin(["b", "c"])

In [50]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [51]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: str

In [52]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [53]:
unique_vals = pd.Series(["c", "b", "a"])

In [54]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [55]:
indices

array([0, 2, 1, 1, 0, 2])

In [56]:
data = pd.DataFrame({"Qu1": [1,3,4,3,4],
                     "Qu2": [2,3,1,2,3],
                     "Qu3": [1,5,2,4,4]})

In [57]:
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [58]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [60]:
result = data.apply(lambda col: col.value_counts()).fillna(0)

In [61]:
result

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0